version: 2
jobs:
  analyze:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - run: echo "RUN_BUILD is ${RUN_BUILD}"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            if [[ ${RUN_BUILD} ]]; then
              npm install --production
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Memory Usage Analysis
          command: |
            if [[ ${RUN_BUILD} ]]; then
              npm run analyze-mem-usage
            fi
          no_output_timeout: '15m'

notify:
  webhooks:
    # gitter hook
    - url: https://webhooks.gitter.im/e/15f197634234d80a32fa
